### ISSUE TITLE
[Suggestion] Return "0" when placeholder return nothing

### ISSUE THREAD

**Issue by NoltoxGit** [Topper-MC/Topper#129]
Helllo,
Would it be possible to add a way so that when a placeholder returns no value (empty), the placeholder returns “0” instead?

This would avoid console errors such as: `[WARN]: [Topper] The placeholder %MY_PLACEHOLDER% returns empty`.

**Comment by HSGamer** [comment]
If you don't care about that, don't enable `show-errors`
